<a href="https://colab.research.google.com/github/AlexSpace07/python/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D1%8F_%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_%E2%84%961_(%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_%E2%84%963).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа по теме: "Введение в анализ данных. Операции над векторами и матрицами в NumPy"

In [1]:
import numpy as np

### Задание 1

Создать 12x12 единичную матрицу (с единицами по диагонали)

In [ ]:
identity_matrix = np.eye(12)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


### Задание 2 *

Создать 9x9 матрицу и заполнить её в шахматном порядке

In [ ]:
chess = np.zeros((9, 9), dtype=int)  # Создаём матрицу из нулей
chess[1::2, ::2] = 1  # Заполняем чётные строки нечётными столбцами
chess[::2, 1::2] = 1  # Заполняем нечётные строки чётными столбцами
print(chess)

[[0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]]


### Задание 3

Отсортировать произвольный вектор в порядке возрастания

In [ ]:
vector = np.random.randint(0, 100, size=(10)) # Создаём произвольный вектор
sorted_vector = sorted(vector)  # Сортируем элементы в порядке возрастания

print("Первоначальный вектор:", vector)
print("Отсортированный вектор:", sorted_vector)

Первоначальный вектор: [96 59 42 75 99 67  4 36 71 91]
Отсортированный вектор: [4, 36, 42, 59, 67, 71, 75, 91, 96, 99]


### Задание 4

Определить есть ли в произвольном двумерном массиве из целых чисел строки, в которых все значения равны 4.

In [27]:
# Произвольный двумерный массив (список списков)
array = np.random.randint(2, 6, size=(5, 3))
print("Массив:")
print(array)

# Проверка, есть ли строки, где все элементы равны 4
has_row_with_all_fours = any(all(x == 4 for x in row) for row in array)

if has_row_with_all_fours:
    print("В массиве есть строки, где все значения равны 4.")
else:
    print("В массиве нет строк, где все значения равны 4.")

Массив:
[[2 2 4]
 [2 5 3]
 [5 5 3]
 [5 3 3]
 [4 4 4]]
В массиве есть строки, где все значения равны 4.


### Задание 5

Создайте массив из 6 элементов, 5 из которых равны 0, последний элемент должен быть равен 1

In [ ]:
# Создание массива из 5 нулей и добавление единицы в конец
array = np.append(np.zeros(5), 1)

print(array)

[0. 0. 0. 0. 0. 1.]


### Задание 6

Укажите индекс 9 элемента в массиве 2х3х2

In [ ]:
# Создаём массив 2x3x2 с рандомными значениями
array = np.random.randint(0, 100, size=(2, 3, 2))  # Диапазон значений от 0 до 100

print("Массив:")
print(array)

# Указываем индекс 9-го элемента
index = np.unravel_index(9, array.shape)

print("Индекс 9-го элемента:", index)
print("9-й элемент:", array[index])

Массив:
[[[25 84]
  [91 61]
  [45 63]]

 [[ 1 53]
  [64 50]
  [52 35]]]
Индекс 9-го элемента: (1, 1, 1)
9-й элемент: 50
